apiVersion: operator.open-cluster-management.io/v1
kind: ClusterPolicy
metadata:
  name: delete-kubeadmin-policy
  namespace: open-cluster-managed
spec:
  remediationAction: enforce
  policy-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: admissionregistration.k8s.io/v1
        kind: MutatingWebhookConfiguration
        metadata:
          name: delete-kubeadmin-webhook
        webhooks:
          - name: delete-kubeadmin
            clientConfig:
              service:
                name: delete-kubeadmin-service
                namespace: open-cluster-management
                path: "/delete-kubeadmin"
            rules:
              - operations: ["DELETE"]
                apiGroups: [""]
                apiVersions: ["v1"]
                resources: ["users"]
---
apiVersion: operator.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: delete-kubeadmin-placementrule
  namespace: open-cluster-managed
spec:
  clusterSelector: {}
  resourceSelectors:
    - apiVersion: apps.open-cluster-management.io/v1
      kind: ManagedCluster
