apiVersion: operator.open-cluster-management.io/v1
kind: ClusterPolicy
metadata:
  name: delete-kubeadmin-user-policy
  namespace: openshift-config-managed
spec:
  remediationAction: enforce
  policy-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: kubeadmin-rolebinding
          namespace: kube-system
        subjects:
          - kind: User
            name: kubeadmin
        roleRef:
          kind: ClusterRole
          name: cluster-admin
          apiGroup: rbac.authorization.k8s.io
---
apiVersion: operator.open-cluster-management.io/v1
kind: Placement
metadata:
  name: delete-kubeadmin-user-placement
  namespace: openshift-config-managed
spec:
  clusterSelector: {}
---
apiVersion: operator.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: delete-kubeadmin-user-binding
  namespace: openshift-config-managed
spec:
  placementRef:
    name: delete-kubeadmin-user-placement
  subjects:
    - kind: User
      name: "cluster-admin"
      apiGroup: rbac.authorization.k8s.io
